apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: cicd
spec:
  type: ClusterIP
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
