apiVersion: v1
kind: PersistentVolume
metadata:
  name: conf-tekton-volume
  namespace: cicd
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/tekton/volumes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace
  namespace: cicd
spec:
  storageClassName: nfs-client
  volumeName: conf-tekton-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
